---
title: ''
output: 
  flexdashboard::flex_dashboard:
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries}
library(tidyverse)
library(scales)
library(readxl)
#library(ipeaData)
library(extrafont)
library(RColorBrewer)
#library(ckanr)
#library(skimr)
library(shiny)
library(leaflet)
library(ggbeeswarm)
library(plotly)
library(viridis)
library(ggrepel)

tema <- function(){
    theme_minimal() +
    theme(
      text = element_text(family = "Open Sans", colour = "grey20"),
      title = element_text(face = "bold", size = 10, color = "#1E4C7A"), 
      plot.subtitle = element_text(family = "Open Sans Condensed", 
                                   color = "grey20", face = "plain", size = 10),
      axis.text = element_text(family = "Open Sans", colour = "grey20", size = 8),
      plot.caption = element_text(face = "italic"),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      axis.ticks = element_line(size = 0.5),
      axis.ticks.length = unit(.25, "cm"),
      axis.title = element_text(size = 8, colour = "grey20"),
      legend.position = 'none')
}

tema_gif <- function() {
  theme(legend.position = 'none',
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        plot.background = element_rect(color = "#f0f5f7", linetype = "solid", size = 2))
}

vermelho <- brewer.pal(3, name = "Set1")[1]
azul <- "#1f476a" 

vermelho_claro <- "#ee7576"
azul_claro     <- "#2c90bf" # "#87b1d4"

tres_cores <-c("#F8AC08","#028063","#6E287C")
tres_cores_pasteis <- c("#FECE60","#63BEAF", "#BE8EBF")

cores_temas_TT <- c("#643275", "#03859a", "#1f476a", "#709a2d", "#ba3917")

load("dados_shiny.RData")

sumario_estados_regionalizado <- sumario_estados_regionalizado %>% 
  mutate(REGIAO = str_sub(REGIAO, 4),
         pop_ranking = rank(-pop),
         dcl_ranking = rank(-pct_DCL_RCL),
         per_cap_ranking = rank(-DCL_pop))


```

<style>
@import url('https://fonts.googleapis.com/css?family=Open+Sans|Open+Sans+Condensed:300');
body {
font-family: "Open Sans";
}
</style>

```{r mun}
sumario_mun <- tabela_municipios %>%
  filter(
    Coluna %in% c("Até o 3º Quadrimestre", "Até o 2º Semestre") & 
      Conta %in% c("% da DCL sobre a RCL (III/RCL)",
                   "DÍVIDA CONSOLIDADA - DC (I)",
                   "DEDUÇÕES (II)",
                   "DÍVIDA CONSOLIDADA LÍQUIDA (DCL) (III) = (I - II)")) %>%
  mutate(Conta = case_when(Conta == "% da DCL sobre a RCL (III/RCL)" ~ "pct_DCL_RCL",
                           Conta == "DÍVIDA CONSOLIDADA LÍQUIDA (DCL) (III) = (I - II)" ~"DCL",
                           Conta == "DÍVIDA CONSOLIDADA - DC (I)" ~ "DC",
                           Conta == "DEDUÇÕES (II)" ~ "Ded")) %>%
  select(REGIAO, Instituicao, Valor, Conta, pop, UF, Escopo, CodMun = Cod.IBGE) %>%
  spread(Conta, Valor, fill = 0) %>%
  mutate(REGIAO = str_sub(REGIAO, 5)) %>%
  left_join(select(perfil_mun, CodMun, nome_mun = `NOME MUNIC`)) %>%
  left_join(estados) %>%
  filter(`Instituicao` != "Prefeitura Municipal de Itaíba - PE") %>%
  mutate(categorias = cut(pct_DCL_RCL, breaks = c(-Inf, 0, 25, 120, Inf),
                          labels = c("DCL negativa", "Até 25% da RCL", "Até 120% da RCL", "Acima do Limite")),
         dcl_pop = DCL / pop,
         rank_dcl_pop = rank(-dcl_pop),
         rank_pop = rank(-pop), 
         rank_DC = rank(-DC),
         rank_DCL_RCL = rank(-pct_DCL_RCL),
         mun_UF = paste0(nome_mun, " - ", UF)) %>%
  group_by(REGIAO) %>%
  mutate(med_DCL_reg = sum(DCL)/n()) %>%
  ungroup() %>%
  group_by(UF) %>%
  mutate(med_DCL_uf = sum(DCL)/n()) %>%
  ungroup()

sumario_mun <- sumario_mun %>%
  group_by(categorias) %>%
  summarise(qde = n()) %>%
  mutate(posicoes = c(-50, 25, 120, 160)) %>%
  right_join(sumario_mun)  

sumario_graf_mun <- function(mun) {
  sumario_mun %>%
    filter(mun_UF == mun) %>%
    select(ded = Ded,
           dc  = DC,
           dcl = DCL,
           med_DCL_uf,
           med_DCL_reg) %>%
    mutate(em_branco = dcl) %>%
    gather(-em_branco, -med_DCL_uf, -med_DCL_reg, key = variavel, value = valor_de_verdade)  %>%
    gather(med_DCL_uf, med_DCL_reg, key = medias, value = valor_media) %>%
    mutate(em_branco = ifelse(variavel == "ded", em_branco, NA)) %>%
    gather(em_branco, valor_de_verdade, key = tipo_valor, value = valor) %>%
    mutate(valor_media = ifelse(variavel == "dcl" & tipo_valor == "valor_de_verdade", valor_media, NA),
           cores = case_when(tipo_valor == "em_branco" ~ "NA",
                             variavel == "dc" ~ azul,
                             variavel == "ded" ~ vermelho,
                             TRUE ~ azul_claro),
           tipo_valor = factor(tipo_valor, 
                               levels = c("valor_de_verdade", "em_branco")),
           variavel = factor(variavel, levels = rev(c("dc", "ded", "dcl"))),
           medias = case_when(medias == "med_DCL_uf" ~ "Média do Estado", 
                              medias == "med_DCL_reg" ~ "Média da Região"))
}

#teste_sp <- sumario_graf_mun("Triunfo - PE")

plota_card_mun <- function(dados) {
  ggplot(dados, aes(x = variavel, y = valor, fill = cores)) + 
    geom_col(position = "stack", width = 0.5) +
    geom_tile(aes(y = valor_media), color = azul, width = 0.7, height = 1, linetype = "dotted") +
    geom_text(aes(y = valor_media, 
                  label = paste0(medias, "\nR$ ", 
                                 format(round(valor_media/1e6, 1), big.mark = ".", decimal.mark = ","), " mi"), 
                  vjust = ifelse(medias == "Média da Região", 2.7, -1.9)), family = "Open Sans Condensed", 
              size = 3.5, color = "dimgrey", hjust = "inward") +
    geom_label(aes(label = ifelse(tipo_valor == "valor_de_verdade" & medias == "Média da Região",
                                 paste0("R$ ", format(round(valor/1e6, 1), 
                                                      big.mark = ".", 
                                                      decimal.mark = ","),
                                        " mi"), 
                                 NA),
                  y = valor,
                  color = cores), 
              family = "Open Sans", size = 3.5, hjust = "center", 
              position = "stack", vjust = "center", fill = "white") +
    scale_fill_identity() + 
    scale_color_identity() +
    scale_y_continuous(labels=function(x) {format(x/1e6, big.mark = ".", decimal.mark=",", scientific = FALSE)}, expand = expand_scale(mult = c(.05, .1))) +
    scale_x_discrete(labels = c("ded" = "Deduções", 
                                "dc"  = "Dívida\nConsolidada", 
                                "dcl" = "Dívida\nConsolidada\nLíquida")) +
    labs(x = NULL, y = "R$ milhões") +
    coord_flip() +
    tema() + theme(axis.text.y = element_text(size = 12)) + theme(axis.line.x = element_line())
}

#plota_card_mun(teste_sp)

# grafio swarm

plota_swarm <- function(mun){
  ggplot(sumario_mun, aes(y = pct_DCL_RCL, x = 0)) +
    geom_quasirandom(varwidth = TRUE, alpha = 1,  
                     aes(color = ifelse(mun_UF == mun, "destaque", "resto"),
                         size = ifelse(mun_UF == mun, "destaque", "resto"))) +
    geom_text(aes(label = ifelse(mun_UF == mun, paste0(mun_UF,"\nDCL/RCL: ", percent(pct_DCL_RCL/100)), NA)), 
              position = position_quasirandom(varwidth = TRUE), vjust = -0.5, 
              hjust = "center", family = "Open Sans", color = "firebrick") +
    scale_size_manual(values = c("destaque" = 2.5, "resto" = 0.5)) +
    scale_color_manual(values = c("destaque" = "firebrick", "resto" = "lightgray")) +
    scale_y_continuous(labels = function(x) {percent(x/100)}, expand = expand_scale(mult = c(0, .15))) +
    labs(y = "% DCL / RCL") +
    tema() + theme(axis.line.x = element_blank(), axis.ticks.x = element_blank(),
                   axis.text.x = element_blank(), axis.title.x = element_blank()) +
    geom_hline(yintercept = 120, linetype = "dotted", color = "dimgrey") + 
    annotate(geom = "text", y = 125, x = -0.42, family = "Open Sans", label = "Limite (120%)",
             size = 2.5, hjust = "inward", vjust = "bottom", color = "dimgrey")
}

retorna_texto_mun <- function(mun, variavel) {
  resultado <- sumario_mun %>%
    filter(mun_UF == mun) %>%
    select(col_interesse = !!sym(variavel)) %>%
    mutate(col_interesse = as.character(col_interesse))
  
  return(as.character(resultado[1,1]))
}

```



```{r}
sumario_grafico <- function(estado) {
  sumario_estados_regionalizado %>%
    filter(UF == estado) %>%
    select(ded = Ded,
           dc  = DC,
           dcl = DCL,
           media_regiao,
           media_nacional) %>%
    mutate(em_branco = dcl) %>%
    gather(-em_branco, -media_regiao, -media_nacional, key = variavel, value = valor_de_verdade)  %>%
    gather(media_regiao, media_nacional, key = medias, value = valor_media) %>%
    mutate(em_branco = ifelse(variavel == "ded", em_branco, NA)) %>%
    gather(em_branco, valor_de_verdade, key = tipo_valor, value = valor) %>%
    mutate(valor_media = ifelse(variavel == "dcl" & tipo_valor == "valor_de_verdade", valor_media, NA),
           cores = case_when(tipo_valor == "em_branco" ~ "NA",
                             variavel == "dc" ~ azul,
                             variavel == "ded" ~ vermelho,
                             TRUE ~ azul_claro),
           tipo_valor = factor(tipo_valor, 
                               levels = c("valor_de_verdade", "em_branco")),
           variavel = factor(variavel, levels = rev(c("dc", "ded", "dcl"))),
           medias = replace(medias, medias == "media_regiao", "Média da Região"),
           medias = replace(medias, medias == "media_nacional", "Média Nacional"))
}

plota_card_estado <- function(dados) {
  ggplot(dados, aes(x = variavel, y = valor, fill = cores)) + 
    geom_col(position = "stack", width = 0.5) +
    geom_tile(aes(y = valor_media), color = azul, width = 0.7, height = 1, linetype = "dotted") +
    geom_text(aes(y = valor_media, 
                  label = paste0(medias, "\nR$ ", 
                                 format(round(valor_media/1e9, 2), big.mark = ".", decimal.mark = ","), " bi"), 
                  vjust = ifelse(medias == "Média Nacional", 2.7, -1.9)), family = "Open Sans Condensed", 
              size = 3.5, color = "dimgrey", hjust = "inward") +
    geom_label(aes(label = ifelse(tipo_valor == "valor_de_verdade" & medias == "Média da Região",
                                 paste0("R$ ", format(round(valor/1e9, 2), 
                                                      big.mark = ".", 
                                                      decimal.mark = ","),
                                        " bi"), 
                                 NA),
                  y = valor,
                  color = cores), 
              family = "Open Sans", size = 3.5, hjust = "center", 
              position = "stack", vjust = "center", fill = "white") +
    scale_fill_identity() + 
    scale_color_identity() +
    scale_y_continuous(labels=function(x) {format(x/1e9, big.mark = ".", decimal.mark=",", scientific = FALSE)}, expand = expand_scale(mult = c(.05, .1))) +
    scale_x_discrete(labels = c("ded" = "Deduções", 
                                "dc"  = "Dívida\nConsolidada", 
                                "dcl" = "Dívida\nConsolidada\nLíquida")) +
    labs(x = NULL, y = "R$ bilhões") +
    coord_flip() +
    tema() + theme(axis.text.y = element_text(size = 12)) + theme(axis.line.x = element_line())
}

#teste_rs <- sumario_grafico("RS")

#plota_card_estado(teste_rs)

mapa_brasil <- geojsonio::geojson_read("./dados/brazil_geo.geojson", what = "sp")
# o ideal seria pegar daqui https://servicodados.ibge.gov.br/api/docs/malhas?versao=2#api-_
# mas só consegui do brasil inteiro, sem as ufs. a api ou renderiza o mapa com ufs ou mostra o json sem ufs.
# aí achei em algum lugar da internet, e só editei um pouco para ficar do jeito esperado, começando com
# {"type":"FeatureCollection","features":[...

# incorporando o dado de DCL no mapa

# testando esse simplify
mapa_brasil <- rmapshaper::ms_simplify(mapa_brasil)

mapa_brasil@data <- sumario_estados %>%
  select(UF, REGIAO, pct_DCL_RCL) %>%
  right_join(mapa_brasil@data, by = c("UF" = "sigla"))

mapa_brasil@data <- mapa_brasil@data %>%
  left_join(estados)

# ggplot(mapa_brasil@data, aes(x = DCL)) + geom_histogram(binwidth = 10) + scale_x_continuous(breaks = seq(-20, 250, 20))

bins <- c(-20, 0, 20, 40, 60, 80, 100, 200, Inf)
pal <- colorBin("YlOrRd", domain = mapa_brasil$DCL, bins = bins)

labels <- sprintf(
  "<strong>%s</strong><br/>DCL/RCL: %g &#37;",
  mapa_brasil$nomes, mapa_brasil$pct_DCL_RCL
) %>% lapply(htmltools::HTML)

faz_mapa <- function() {
  leaflet(mapa_brasil, options = leafletOptions(minZoom = 3.7, maxZoom = 4.5, dragging = FALSE)) %>%
    setView(lat=-14.235, lng=-51.9253 , zoom=4.5) %>%
    addPolygons(
      fillColor = ~pal(pct_DCL_RCL),
      weight = 3,
      opacity = 1,
      color = "white",
      fillOpacity = 0.8,
      highlight = highlightOptions(
        weight = 3,
        color = "#353E57",
        fillOpacity = 1,
        bringToFront = TRUE),
      label = labels,
      layerId = ~UF,  # muito importante, vai alimentar o "id" do shape_click
      labelOptions = labelOptions(
        style = list("font-weight" = "normal",
                     "font-family" = "'Open Sans'",
                     padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"))
}

#  addProviderTiles("MapBox", options = providerTileOptions(
#    id = "mapbox.light",
#    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%

retorna_texto <- function(estado, variavel) {
  resultado <- sumario_estados_regionalizado %>%
    filter(UF == estado) %>%
    select(!!sym(variavel))
  return (as.character(resultado[1,1]))
}

# retorna_texto("AC", "nomes")


```

Estados
===================================== 

Column 
-----------------------------------------------------------------------

### Os estados estão coloridos no mapa de acordo com sua relação DCL / RCL. Clique num Estado no mapa para obter mais informações.

```{r}
leafletOutput("mapa")

output$mapa <- renderLeaflet({
  faz_mapa()
  })
    
obtem_estado_click <- function() {
   click <- input$mapa_shape_click
   if (is.null(click))
     uf <- "AC"
   else
     uf <- click$id
   return(uf)
   }


```

Column 
-----------------------------------------------------------------------

### Dados obtidos do Relatório de Gestão Fiscal de 2018

```{r}
mainPanel(width = "90%", height = "90%",
  textOutput("Estado"),
  textOutput("regiao"),
  tagAppendAttributes(textOutput("pop"), style="font-family: 'Open Sans'"),
  #textOutput("DCLperCap"),
  tags$style(type="text/css", "#Estado {font-family: 'Open Sans'; font-size: 2em; color: #1f476a; padding-bottom: 5px; font-weight: 400;}"),
  tags$style(type="text/css", "#regiao {font-family: 'Open Sans'; font-size: 1.5em; padding-bottom: 5px; padding-top: 5px;}"),
  tagAppendAttributes(textOutput("DCL_RCL", container = span), style="font-family: 'Open Sans'"),
  tagAppendAttributes(textOutput("DCL_RCL_valor_acima", container = span), style="font-family: 'Open Sans';
                      color: firebrick;"),
  tagAppendAttributes(textOutput("DCL_RCL_valor_abaixo", container = span), style="font-family: 'Open Sans';"),
  tagAppendAttributes(textOutput("rankingDCL", container = span), style="font-family: 'Open Sans'"),
  tagAppendAttributes(textOutput("DCLperCap"), style="font-family: 'Open Sans'"),
  plotOutput("card")
)

# melhorar isso aqui. pegar o click uma vez só; talvez usar um input dummy.

output$Estado    <- renderText(retorna_texto(obtem_estado_click(), "nomes"))
output$regiao    <- renderText(paste0("Região ", retorna_texto(obtem_estado_click(), "REGIAO")))
output$pop       <- renderText(paste0("População: ",
                                      format(
                                        round(
                                          as.numeric(
                                            retorna_texto(obtem_estado_click(), "pop")
                                            ),
                                          2),
                                        big.mark = ".", decimal.mark = ","),
                                      " pessoas",
                                      " (é o ",
                                      retorna_texto(obtem_estado_click(), "pop_ranking"),
                                      "º mais populoso)."))

output$DCL_RCL <- renderText("A DCL do Estado corresponde a ")

output$DCL_RCL_valor_acima <- function(){
  vlr <- as.numeric(retorna_texto(obtem_estado_click(), "pct_DCL_RCL"))
  if (vlr >= 200) {
    return(paste0(percent(round(vlr/100,2)), " de sua RCL"))
  } else {
    return("")
  }
}

output$DCL_RCL_valor_abaixo <- function(){
  vlr <- as.numeric(retorna_texto(obtem_estado_click(), "pct_DCL_RCL"))
  if (vlr >= 200) {
    return("")
  } else {
    return(paste0(percent(round(vlr/100,2)), " de sua RCL"))
  }
}
                                  
output$rankingDCL <- renderText(paste0(" (é a ", retorna_texto(obtem_estado_click(), "dcl_ranking"),
                                       "ª maior relação DCL/RCL)."))

output$DCLperCap <- renderText(paste0("DCL por habitante: R$ ",
   format(round(as.numeric(retorna_texto(obtem_estado_click(), "DCL_pop")),2),
                                       big.mark = ".", decimal.mark = ","),
   " (é a ", retorna_texto(obtem_estado_click(), "per_cap_ranking"),
                                       "ª maior DCL per capita)."))

output$card <- renderPlot(
  plota_card_estado(sumario_grafico(obtem_estado_click())), width = "auto", height = 400)





```

Municípios
===================================== 


Column 
-----------------------------------------------------------------------

### Escolha o município

```{r}
mainPanel(width = "95%",
  selectInput("mun", label = "", choices = sumario_mun$mun_UF, selected = "Imbituba - SC", multiple = FALSE),
  plotOutput("swarm")
  )

output$swarm <- renderPlot(plota_swarm(input$mun), width = "auto", height = 400)
```

Column 
-----------------------------------------------------------------------

### Informações do município

```{r}
mainPanel(width = "95%",
  textOutput("Municipio"),
  tags$style(type="text/css", "#Municipio {font-family: 'Open Sans'; font-size: 2em; color: #1f476a; padding-bottom: 5px; font-weight: bold;}"),
  tagAppendAttributes(textOutput("mun_UF"), style="font-family: 'Open Sans'; font-size: 1.7em; padding-bottom: 3px; font-weight: 400;"),
  textOutput("reg"),
  tags$style(type="text/css", "#reg {font-family: 'Open Sans'; font-size: 1.5em; padding-bottom: 5px; padding-top: 5px;}"),
  tagAppendAttributes(textOutput("mun_pop"), style="font-family: 'Open Sans'"),
  tagAppendAttributes(textOutput("mun_DCL_RCL", container = span), style="font-family: 'Open Sans'"),
  tagAppendAttributes(textOutput("mun_DCL_RCL_valor_acima", container = span), style="font-family: 'Open Sans'; color: firebrick;"),
  tagAppendAttributes(textOutput("mun_DCL_RCL_valor_abaixo", container = span), style="font-family: 'Open Sans';"),
  tagAppendAttributes(textOutput("mun_rankingDCL", container = span), style="font-family: 'Open Sans'"),
  tagAppendAttributes(textOutput("mun_DCLperCap"), style="font-family: 'Open Sans'"),
  plotOutput("mun_card")
)
  
output$Municipio    <- renderText(retorna_texto_mun(input$mun, "nome_mun"))
output$reg    <- renderText(paste0("Região ", retorna_texto_mun(input$mun, "REGIAO")))
output$mun_UF    <- renderText(retorna_texto_mun(input$mun, "nomes"))
output$mun_pop       <- renderText(paste0("População: ",
                                      format(
                                        round(
                                          as.numeric(
                                            retorna_texto_mun(input$mun, "pop")
                                            ),
                                          2),
                                        big.mark = ".", decimal.mark = ","),
                                      " pessoas",
                                      " (é o ",
                                      retorna_texto_mun(input$mun, "rank_pop"),
                                      "º mais populoso)."))

output$mun_DCL_RCL <- renderText("A DCL do município corresponde a ")

output$mun_DCL_RCL_valor_acima <- function(){
  vlr <- as.numeric(retorna_texto_mun(input$mun, "pct_DCL_RCL"))
  if (vlr >= 120) {
    return(paste0(percent(round(vlr/100,2)), " de sua RCL"))
  } else {
    return("")
  }
}

output$mun_DCL_RCL_valor_abaixo <- function(){
  vlr <- as.numeric(retorna_texto_mun(input$mun, "pct_DCL_RCL"))
  if (vlr >= 120) {
    return("")
  } else {
    return(paste0(percent(round(vlr/100,2)), " de sua RCL"))
  }
}
                                  
output$mun_rankingDCL <- renderText(paste0(" (é a ", retorna_texto_mun(input$mun, "rank_DCL_RCL"),
                                       "ª maior relação DCL/RCL)."))

output$mun_DCLperCap <- renderText(paste0("DCL por habitante: R$ ",
   format(round(as.numeric(retorna_texto_mun(input$mun, "dcl_pop")),2),
                                       big.mark = ".", decimal.mark = ","),
   " (é a ", retorna_texto_mun(input$mun, "rank_dcl_pop"),
                                       "ª maior DCL per capita)."))

output$mun_card <- renderPlot(
  plota_card_mun(sumario_graf_mun(input$mun)), width = "auto", height = 400)

```
